# 1.环境配置
spring.application.name=new-office-automation-backend
spring.profiles.active=dev

# 2. MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# HikariCP数据库连接池
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# 3. MyBatis
# 自动转驼峰
mybatis.configuration.map-underscore-to-camel-case=true

# 4. 目录
# 根目录
file.base-path=E:/TheFinishedHomwork
# 头像上传路径
file.avatar-path=${file.base-path}/uploads/avatar/
# 文件上传路径
file.office-path=${file.base-path}/uploads/office/

# 5. 文件
# 文件大小限制 (10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# 6. JWT 生成密钥
jwt.secret-key=office_automation_system_backend_secret_key_2026_safe

# 7. Redis
spring.data.redis.database=0
spring.data.redis.timeout=5000ms
spring.data.redis.username=default
