# JWT 生成密钥
jwt.secret-key=${JWT_SECRET_KEY}

# 目录
# 根目录
file.base-path=/app
# 头像上传路径
file.avatar-path=${file.base-path}/uploads/avatar/
# 文件上传路径
file.office-path=${file.base-path}/uploads/office/

# 数据库重要配置
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Redis重要配置
spring.data.redis.host=${SPRING_DATA_REDIS_HOST}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT}
spring.data.redis.password=${SPRING_DATA_REDIS_PASSWORD}