#环境配置
spring.application.name=new-office-automation-backend
spring.profiles.active=dev

# MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# HikariCP数据库连接池
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# MyBatis
# 自动转驼峰
mybatis.configuration.map-underscore-to-camel-case=true


# 文件
# 文件大小限制 (10MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# 业务配置
app.default-password=123456

# Redis
spring.data.redis.database=0
spring.data.redis.timeout=5000ms
spring.data.redis.username=default
